main: main.c

	

	AVRDUDE_PROGRAMMER = stk500v2

# com1 = serial port. Use lpt1 to connect to parallel port.
AVRDUDE_PORT = com3    # programmer connected to serial device

AVRDUDE_WRITE_FLASH = -U flash:w:main.hex